# Curated directory of cybersecurity tools relevant to law-enforcement / cyber-crime
# investigation. Categorised by `type` (ai-agentic | ai | open-source | commercial)
# and `category` (functional area). This is static reference content.

TYPES = [
    {"id": "ai-agentic", "label": "AI Agentic"},
    {"id": "ai", "label": "AI-Assisted"},
    {"id": "open-source", "label": "Open Source / Manual"},
    {"id": "commercial", "label": "Commercial"},
]

TOOLS = [
    # ----------------------------- AI AGENTIC -----------------------------
    {
        "id": "pentestgpt", "name": "PentestGPT", "type": "ai-agentic",
        "category": "Offensive / Pentest",
        "description": "An LLM-driven assistant that guides an operator through a penetration test, reasoning about next steps, parsing tool output and suggesting exploitation paths.",
        "usage": "Feed it recon/scan output; it proposes the next action and explains the reasoning. Acts as an interactive co-pilot for authorised testing.",
        "best_case": "Up-skilling officers on offensive techniques while assessing the security of a seized server or suspect's authorised infrastructure.",
        "tags": ["LLM", "pentest", "co-pilot"],
        "url": "https://github.com/GreyDGL/PentestGPT",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "security-copilot", "name": "Microsoft Security Copilot", "type": "ai-agentic",
        "category": "Incident Response",
        "description": "Generative-AI security analyst that triages incidents, summarises threat intelligence and writes investigation queries across the Microsoft security stack.",
        "usage": "Ask natural-language questions about an incident; it correlates signals, builds timelines and drafts response steps.",
        "best_case": "A cyber cell SOC triaging a high volume of alerts and needing fast, explainable incident summaries.",
        "tags": ["GenAI", "SOC", "triage"],
        "url": "https://www.microsoft.com/security/business/ai-machine-learning/microsoft-security-copilot",
        "open_source": False, "pricing": "Commercial",
    },
    {
        "id": "cai", "name": "CAI (Cybersecurity AI)", "type": "ai-agentic",
        "category": "Offensive / Pentest",
        "description": "Open-source framework for building autonomous AI security agents that can run recon, exploitation and reporting workflows.",
        "usage": "Compose agents and tools to automate parts of an assessment; integrates with common offensive tooling.",
        "best_case": "Research labs and forensic units experimenting with autonomous, auditable security testing.",
        "tags": ["agents", "framework", "automation"],
        "url": "https://github.com/aliasrobotics/cai",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "nebula", "name": "Nebula", "type": "ai-agentic",
        "category": "Offensive / Pentest",
        "description": "AI-powered penetration-testing assistant that interprets tool output and recommends commands for the next phase.",
        "usage": "Pipe in scan results; Nebula suggests follow-up commands and notes findings automatically.",
        "best_case": "Speeding up repetitive recon-to-exploit transitions during an authorised assessment.",
        "tags": ["recon", "assistant"],
        "url": "https://github.com/berylliumsec/nebula",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "hackingbuddygpt", "name": "hackingBuddyGPT", "type": "ai-agentic",
        "category": "Offensive / Pentest",
        "description": "Research project using LLM agents to autonomously attempt privilege escalation and host compromise in lab environments.",
        "usage": "Point it at an authorised lab host; the agent iterates on commands to reach an objective and logs its reasoning.",
        "best_case": "Academic / training study of how autonomous agents approach exploitation.",
        "tags": ["research", "privilege-escalation"],
        "url": "https://github.com/ipa-lab/hackingBuddyGPT",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "garak", "name": "garak (NVIDIA)", "type": "ai-agentic",
        "category": "AI / LLM Security",
        "description": "Vulnerability scanner for large language models — probes for prompt injection, jailbreaks, data leakage and toxic output.",
        "usage": "Run probe suites against a target LLM endpoint to enumerate weaknesses and produce a report.",
        "best_case": "Assessing the safety of an AI chatbot implicated in a fraud or impersonation case.",
        "tags": ["LLM", "red-team", "scanner"],
        "url": "https://github.com/NVIDIA/garak",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "reconaizer", "name": "ReconAIzer", "type": "ai-agentic",
        "category": "OSINT / Recon",
        "description": "Burp Suite extension that uses OpenAI to suggest recon leads — endpoints, parameters and likely attack surface — from observed traffic.",
        "usage": "Install in Burp; it augments captured requests with AI-generated recon suggestions.",
        "best_case": "Web-app investigations where you need rapid attack-surface ideas from intercepted traffic.",
        "tags": ["burp", "recon", "web"],
        "url": "https://github.com/hisxo/ReconAIzer",
        "open_source": True, "pricing": "Free",
    },

    # ----------------------------- AI-ASSISTED -----------------------------
    {
        "id": "darktrace", "name": "Darktrace", "type": "ai",
        "category": "Network Detection",
        "description": "Self-learning AI that models 'normal' for a network and flags anomalous behaviour indicative of intrusion or insider threat.",
        "usage": "Deploys passively; learns baselines and raises prioritised anomaly alerts with autonomous response options.",
        "best_case": "Detecting lateral movement or data exfiltration on a victim organisation's network during an active breach.",
        "tags": ["anomaly", "NDR", "insider-threat"],
        "url": "https://www.darktrace.com",
        "open_source": False, "pricing": "Commercial",
    },
    {
        "id": "virustotal", "name": "VirusTotal (Code Insight)", "type": "ai",
        "category": "Malware / Threat Intel",
        "description": "Reputation engine for files, URLs, domains and IPs aggregating 70+ AV engines, now with AI-generated natural-language summaries of malware behaviour.",
        "usage": "Submit a hash/URL/file; review multi-engine verdicts, relationships and the AI behaviour summary.",
        "best_case": "Rapid triage of a suspicious attachment or link reported by a complainant.",
        "tags": ["reputation", "malware", "threat-intel"],
        "url": "https://www.virustotal.com",
        "open_source": False, "pricing": "Freemium",
    },
    {
        "id": "vectra", "name": "Vectra AI", "type": "ai",
        "category": "Network Detection",
        "description": "AI-driven network detection and response that scores attacker behaviours across cloud, identity and network.",
        "usage": "Ingests network/identity telemetry and surfaces prioritised, attacker-behaviour-based detections.",
        "best_case": "Hunting an active intruder across hybrid infrastructure in a corporate breach case.",
        "tags": ["NDR", "threat-hunting"],
        "url": "https://www.vectra.ai",
        "open_source": False, "pricing": "Commercial",
    },
    {
        "id": "maltego", "name": "Maltego", "type": "ai",
        "category": "OSINT / Link Analysis",
        "description": "Graph-based link-analysis platform that visualises relationships between people, emails, phones, domains, social accounts and crypto wallets.",
        "usage": "Run 'transforms' on an entity to pull related data and build an investigative graph.",
        "best_case": "Mapping an organised cyber-fraud network from a single phone number or email to its wider footprint.",
        "tags": ["graph", "OSINT", "link-analysis"],
        "url": "https://www.maltego.com",
        "open_source": False, "pricing": "Freemium",
    },

    # ----------------------------- OPEN SOURCE / MANUAL -----------------------------
    {
        "id": "nmap", "name": "Nmap", "type": "open-source",
        "category": "Network Scanning",
        "description": "The de-facto network mapper for host discovery, port scanning, service/version detection and OS fingerprinting via the NSE scripting engine.",
        "usage": "`nmap -sV -sC <target>` to enumerate open ports, services and run safe detection scripts.",
        "best_case": "Profiling the exposed services of a suspect server or C2 host (the deeper engine behind this app's Port Scanner).",
        "tags": ["ports", "recon", "network"],
        "url": "https://nmap.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "wireshark", "name": "Wireshark", "type": "open-source",
        "category": "Network Forensics",
        "description": "World-standard packet analyser for capturing and dissecting network traffic at the protocol level.",
        "usage": "Open a PCAP or capture live; filter (e.g. `http`, `dns`, `tcp.stream`) to follow conversations and extract artefacts.",
        "best_case": "Analysing captured traffic to prove data exfiltration or identify C2 communication.",
        "tags": ["pcap", "packets", "protocol"],
        "url": "https://www.wireshark.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "autopsy", "name": "Autopsy / The Sleuth Kit", "type": "open-source",
        "category": "Disk Forensics",
        "description": "GUI digital-forensics platform over The Sleuth Kit for analysing disk images — timelines, deleted files, keyword search, web/registry artefacts.",
        "usage": "Ingest a forensic image; run modules for file recovery, timeline and keyword hits, then export findings.",
        "best_case": "Examining a seized hard drive for evidence in a fraud or CSAM investigation.",
        "tags": ["disk", "forensics", "recovery"],
        "url": "https://www.autopsy.com",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "volatility", "name": "Volatility", "type": "open-source",
        "category": "Memory Forensics",
        "description": "Advanced memory-forensics framework to extract processes, network connections, injected code and credentials from RAM images.",
        "usage": "`vol.py -f mem.raw <plugin>` to list processes, dump artefacts and detect injected malware.",
        "best_case": "Recovering encryption keys or running malware from a live-captured memory image of a suspect machine.",
        "tags": ["memory", "RAM", "malware"],
        "url": "https://www.volatilityfoundation.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "shodan", "name": "Shodan", "type": "open-source",
        "category": "OSINT / Recon",
        "description": "Search engine for internet-connected devices — servers, webcams, ICS/SCADA and exposed databases — with banners and known vulnerabilities.",
        "usage": "Query by IP, org, port or product to discover a target's internet-facing footprint and exposures.",
        "best_case": "Locating exposed devices or open databases tied to an IP under investigation.",
        "tags": ["OSINT", "exposure", "search"],
        "url": "https://www.shodan.io",
        "open_source": False, "pricing": "Freemium",
    },
    {
        "id": "theharvester", "name": "theHarvester", "type": "open-source",
        "category": "OSINT / Recon",
        "description": "Gathers emails, subdomains, hosts and employee names for a domain from public sources — a fast OSINT footprinting tool.",
        "usage": "`theHarvester -d <domain> -b all` to collate a domain's exposed contact and host surface.",
        "best_case": "Building an initial OSINT profile of a phishing domain or suspect organisation.",
        "tags": ["OSINT", "email", "subdomains"],
        "url": "https://github.com/laramies/theHarvester",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "spiderfoot", "name": "SpiderFoot", "type": "open-source",
        "category": "OSINT / Recon",
        "description": "Automated OSINT collection engine with 200+ modules that pivots across IPs, domains, emails, names and breaches.",
        "usage": "Start a scan on a seed entity; it auto-correlates data from dozens of sources into a single report.",
        "best_case": "Hands-off, broad OSINT sweep on a suspect identifier early in an investigation.",
        "tags": ["OSINT", "automation"],
        "url": "https://github.com/smicallef/spiderfoot",
        "open_source": True, "pricing": "Freemium",
    },
    {
        "id": "exiftool", "name": "ExifTool", "type": "open-source",
        "category": "Media Forensics",
        "description": "Reads and writes metadata in images, documents and media — GPS coordinates, device make/model, timestamps and edit history.",
        "usage": "`exiftool <file>` to dump all embedded metadata, including hidden geotags and software fingerprints.",
        "best_case": "Geolocating or identifying the source device of an image in a harassment or CSAM case.",
        "tags": ["metadata", "EXIF", "images"],
        "url": "https://exiftool.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "hashcat", "name": "Hashcat", "type": "open-source",
        "category": "Password Recovery",
        "description": "World's fastest GPU-accelerated password-recovery tool supporting hundreds of hash types and attack modes.",
        "usage": "`hashcat -m <mode> hashes.txt wordlist.txt` to recover plaintext from captured hashes.",
        "best_case": "Recovering passwords from a seized device's hash store under proper legal authority.",
        "tags": ["password", "cracking", "GPU"],
        "url": "https://hashcat.net/hashcat/",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "john", "name": "John the Ripper", "type": "open-source",
        "category": "Password Recovery",
        "description": "Veteran password-cracking suite with smart rule-based and dictionary attacks across many formats.",
        "usage": "`john --wordlist=rockyou.txt hashes.txt` to test captured credentials for weak passwords.",
        "best_case": "Auditing or recovering weak credentials from seized password databases.",
        "tags": ["password", "cracking"],
        "url": "https://www.openwall.com/john/",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "metasploit", "name": "Metasploit Framework", "type": "open-source",
        "category": "Offensive / Pentest",
        "description": "Comprehensive exploitation framework with thousands of exploits, payloads and post-exploitation modules.",
        "usage": "Select a module, set options, and run against an authorised target to validate a vulnerability.",
        "best_case": "Validating whether a vulnerability on a seized/authorised host is genuinely exploitable.",
        "tags": ["exploit", "pentest"],
        "url": "https://www.metasploit.com",
        "open_source": True, "pricing": "Freemium",
    },
    {
        "id": "burp", "name": "Burp Suite", "type": "open-source",
        "category": "Web Application",
        "description": "Industry-standard web-app testing proxy for intercepting, modifying and analysing HTTP(S) traffic and finding web vulnerabilities.",
        "usage": "Proxy browser traffic through Burp; use Repeater/Intruder to probe a target web application.",
        "best_case": "Investigating a phishing kit or vulnerable web portal hosted by a suspect.",
        "tags": ["web", "proxy", "appsec"],
        "url": "https://portswigger.net/burp",
        "open_source": False, "pricing": "Freemium",
    },
    {
        "id": "ghidra", "name": "Ghidra", "type": "open-source",
        "category": "Reverse Engineering",
        "description": "NSA-developed software reverse-engineering suite with a powerful decompiler for analysing malware binaries.",
        "usage": "Import a binary; use the decompiler and disassembler to understand malware behaviour and IOCs.",
        "best_case": "Reverse-engineering a novel malware sample seized in a ransomware investigation.",
        "tags": ["RE", "decompiler", "malware"],
        "url": "https://ghidra-sre.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "cuckoo", "name": "Cuckoo Sandbox", "type": "open-source",
        "category": "Malware Analysis",
        "description": "Automated malware-analysis sandbox that detonates suspicious files in isolation and reports behaviour, network and dropped files.",
        "usage": "Submit a sample; review the automated behavioural report (API calls, network, persistence).",
        "best_case": "Safely understanding what a suspicious attachment does before further action.",
        "tags": ["sandbox", "malware", "dynamic"],
        "url": "https://cuckoosandbox.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "misp", "name": "MISP", "type": "open-source",
        "category": "Threat Intelligence",
        "description": "Open threat-intelligence platform for storing, correlating and sharing indicators of compromise between agencies.",
        "usage": "Ingest IOCs, correlate across events and share curated intel with partner units.",
        "best_case": "Inter-agency sharing of indicators from a coordinated cyber-fraud crackdown.",
        "tags": ["IOC", "threat-intel", "sharing"],
        "url": "https://www.misp-project.org",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "recon-ng", "name": "Recon-ng", "type": "open-source",
        "category": "OSINT / Recon",
        "description": "Modular, Metasploit-style framework for web-based open-source reconnaissance and data harvesting.",
        "usage": "Load modules, set a workspace and run recon against a target domain or identity.",
        "best_case": "Structured, repeatable OSINT collection with stored workspaces per case.",
        "tags": ["OSINT", "framework"],
        "url": "https://github.com/lanmaster53/recon-ng",
        "open_source": True, "pricing": "Free",
    },
    {
        "id": "aircrack", "name": "Aircrack-ng", "type": "open-source",
        "category": "Wireless",
        "description": "Suite for assessing Wi-Fi network security — capture, replay and crack WEP/WPA-PSK keys.",
        "usage": "Capture handshakes with airodump-ng, then crack with aircrack-ng against a wordlist.",
        "best_case": "Assessing or proving compromise of a wireless network in an authorised investigation.",
        "tags": ["wifi", "wireless", "cracking"],
        "url": "https://www.aircrack-ng.org",
        "open_source": True, "pricing": "Free",
    },

    # ----------------------------- COMMERCIAL FORENSICS -----------------------------
    {
        "id": "cellebrite", "name": "Cellebrite UFED", "type": "commercial",
        "category": "Mobile Forensics",
        "description": "Industry-leading mobile-device forensic platform for lawful extraction and decoding of data from phones and apps.",
        "usage": "Connect a seized device; perform logical/physical extraction and analyse messages, media and app data.",
        "best_case": "Lawfully extracting chats, call logs and deleted media from a suspect's seized smartphone.",
        "tags": ["mobile", "extraction", "forensics"],
        "url": "https://cellebrite.com",
        "open_source": False, "pricing": "Commercial",
    },
    {
        "id": "magnet-axiom", "name": "Magnet AXIOM", "type": "commercial",
        "category": "Digital Forensics",
        "description": "Unified digital-investigation platform acquiring and analysing evidence from computers, mobile and cloud in one case file.",
        "usage": "Acquire sources, then use Connections and timeline views to correlate artefacts across devices.",
        "best_case": "Building a single, court-ready evidence picture from a suspect's phone, laptop and cloud accounts.",
        "tags": ["forensics", "cloud", "timeline"],
        "url": "https://www.magnetforensics.com",
        "open_source": False, "pricing": "Commercial",
    },
    {
        "id": "oxygen", "name": "Oxygen Forensic Detective", "type": "commercial",
        "category": "Mobile Forensics",
        "description": "All-in-one forensic suite for extracting and analysing data from mobile devices, drones, cloud services and IoT.",
        "usage": "Extract device/cloud data and analyse messengers, locations and account links.",
        "best_case": "Comprehensive extraction across a suspect's mobile and connected-cloud ecosystem.",
        "tags": ["mobile", "cloud", "IoT"],
        "url": "https://oxygenforensics.com",
        "open_source": False, "pricing": "Commercial",
    },
    {
        "id": "chainalysis", "name": "Chainalysis Reactor", "type": "commercial",
        "category": "Crypto Investigation",
        "description": "Blockchain-analytics platform that traces cryptocurrency transactions and clusters wallets to real-world entities and exchanges.",
        "usage": "Enter a wallet/transaction; visualise fund flows and identify cash-out points for legal requests.",
        "best_case": "Tracing stolen funds in a crypto-investment-fraud case to an exchange for KYC subpoena.",
        "tags": ["crypto", "blockchain", "tracing"],
        "url": "https://www.chainalysis.com",
        "open_source": False, "pricing": "Commercial",
    },
]


def get_catalog() -> dict:
    categories = sorted({t["category"] for t in TOOLS})
    return {"types": TYPES, "categories": categories, "tools": TOOLS, "count": len(TOOLS)}
